server:
    port: 8687

spring:
    application:
        name: eureka-service

eureka:
    instance:
        hostname: localhost:8687
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}/eureka/
